name: Deploy FastAPI to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
        # ADD THIS LINE:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        # ADD THIS to the envs list:
        envs: ENV_FILE,GCP_SA_KEY
        script: |
          cd /home/moltafet_ahmad2015/olleey-backend
          git reset --hard origin/main
          git pull origin main
          
          # Write the secrets to files
          echo "$ENV_FILE" > .env
          # ADD THIS LINE (Creates the JSON file on the server):
          echo "$GCP_SA_KEY" > vox-translate-b8c94-firebase-adminsdk-fbsvc-7749166547.json
          
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart fastapi_app