name: Deploy FastAPI to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        envs: ENV_FILE
        script: |
          # 1. Go to the project folder
          cd /home/moltafet_ahmad2015/olleey-backend
          
          # 2. Update Code
          git reset --hard origin/main
          git pull origin main
          
          # 3. OVERWRITE .env file with the one from GitHub Secrets
          echo "$ENV_FILE" > .env
          
          # 4. Install Dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          
          # 5. Restart the App to apply changes
          sudo systemctl restart fastapi_app